# action
# description: lists all workflows in a Temporal namespace, paginated in batches of 100.
name    = "temporal_workflow_list"
label   = "temporal"
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name = "list workflows"
inline_contents = "./temporal/temporal_workflow_list/list_workflows.sh"

[steps.env_vars]
NAMESPACE = "general"
