# action
# description: lists the most recent running workflows for each Temporal namespace.
name    = "temporal_workflow_list"
labels  = { service = "temporal", type = "debug" }
label   = "temporal"
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name = "list workflows"
inline_contents = "./temporal/temporal_workflow_list/list_workflows.sh"

[steps.env_vars]
LIMIT = "10"
