# action
name    = "kill_pods_in_namespace"
labels  = { service = "kubernetes", type = "tool" }
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kill-pods-in-namespace"
inline_contents = "./kubectl/kill_pods_in_namespace/kill-pods-in-namespace.sh"

[steps.env_vars]
NAMESPACE = ""
