# action
name    = "karpenter_nodepools"
labels  = { layer = "infra", purpose = "debug" }
timeout = "20s"


[[triggers]]
type          = "cron"
cron_schedule = "*/20 */1 * * *"  # https://crontab.guru/#*/20_*/1_*_*_*

[[triggers]]
type = "manual"

[[steps]]
name            = "list"
inline_contents = "./karpenter/karpenter_nodepools/nodepools.sh"
