#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "karpenter_nodepools"
labels  = { service = "karpenter", type = "debug" }
timeout = "20s"


[[triggers]]
type          = "cron"
cron_schedule = "*/20 */1 * * *"  # https://crontab.guru/#*/20_*/1_*_*_*

[[triggers]]
type = "manual"

[[steps]]
name            = "list"
inline_contents = "./karpenter/karpenter_nodepools/nodepools.sh"
