#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "ctl_api_query_workflows_in_flight"
label   = "query"
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name            = "Query in-flight workflows"
inline_contents = "./ctl_api/ctl_api_query_workflows_in_flight/query-workflows-in-flight.sh"

[steps.env_vars]
DB_USER        = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_username }}"
DB_NAME        = "ctl_api"
SECRET_ARN     = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_master_user_secret_arn }}"
DB_ADDR        = "{{ .nuon.components.rds_cluster_nuon.outputs.address }}"
DB_PORT        = "5432"
REGION         = "{{ .nuon.install_stack.outputs.region }}"
SINCE          = "2 weeks"
LIMIT          = "100"
