name         = "phone_home_secret_role_arn"
description  = "Role ARN for provisioning and confifuring Install Phone Home Secrets"
default      = ""
display_name = "Phone Home Secret Role ARN"
required     = false
group        = "phone_home"

user_configurable = false
