type = "maintenance"
name                 = "{{ .nuon.install.id }}-maintenance"
description          = "maintenance"
display_name         = "byoc-nuon maintenance role"
permissions_boundary = "./maintenance_boundary.json"

[[policies]]
managed_policy_name = "AdministratorAccess"

# NOTE: the tag in this policy is determined by the rds_cluster_* component config. the format is known ahead of time by
# convention.
[[policies]]
name = "{{ .nuon.install.id }}-limited-secrets-manager-rds"
contents = "./rds-secret.json"

[[policies]]
name = "{{ .nuon.install.id }}-allow-secret-list"
contents = "./secrets-list.json"

[[policies]]
name = "bucket-put-policy-scoped"
contents = "./bucket-put-policy.json"
