type                 = "provision"
name                 = "{{.nuon.install.id}}-provision"
description          = "Provision role for BYOC Nuon Install {{ .nuon.install.id }}"
display_name         = "Provision Role {{.nuon.install.id}}"
permissions_boundary = "./provision_boundary.json"

[[policies]]
managed_policy_name = "AdministratorAccess"

