# action
name    = "inspect_install"
labels  = { service = "ctl-api", type = "debug" }
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name = "timestamp"
inline_contents = '''
#!/usr/bin/env bash
set -euo pipefail
jq -nc --arg ts "$(TZ=UTC date +%Y-%m-%dT%H:%M:%SZ)" '{updated_at: $ts}' >> $NUON_ACTIONS_OUTPUT_FILEPATH
'''

[[steps]]
name            = "install"
inline_contents = "./ctl_api/inspect_install/inspect-install.sh"

[steps.env_vars]
INSTALL_ID = ""
DB_USER    = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_username }}"
DB_NAME    = "ctl_api"
SECRET_ARN = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_master_user_secret_arn }}"
DB_ADDR    = "{{ .nuon.components.rds_cluster_nuon.outputs.address }}"
DB_PORT    = "5432"
REGION     = "{{ .nuon.install_stack.outputs.region }}"
