# action
name    = "ctl_api_post_deploy_startup"
labels  = { service = "ctl-api", type = "step" }
timeout = "1m30s"

[[triggers]]
type           = "post-deploy-component"
component_name = "ctl_api"
index          = 1

[[triggers]]
type = "manual"

[[steps]]
name            = "startup"
inline_contents = "./ctl_api/ctl_api_post_deploy_startup/startup.sh"

[steps.env_vars]
DB_ADDR = "{{ .nuon.components.cloudsql_nuon.outputs.address }}"
DB_PORT = "5432"
