# generated on: 2025-06-09 18:57:06.390531+00:00

# 8-email.toml
#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "email"
description  = "Configure email settings."
display_name = "Email"

[[input]]
name         = "loops_api_key"
description  = "An API key from your loops account."
default      = "your-loops-api-key"
display_name = "Loops API Key"
group        = "email"
required     = false
