# generated on: 2025-05-15 02:56:12.498835+00:00

# 1-rds-nuon.toml
#:schema https://api.nuon.co/v1/general/config-schema?source=inputS
[[group]]
name         = "rds-nuon"
description  = "Configuration for the postgres database Nuon will create for itself."
display_name = "Nuon database configuration"

[[input]]
name         = "nuon_db_instance_type"
description  = "What RDS DB instance type would you like to deploy for nuon?"
default      = "db.t4g.medium"
display_name = "RDS Instance Type"
group        = "rds-nuon"


# 2-rds-temporal.toml
#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "rds-temporal"
description  = "Configuration for the postgres database Nuon will create for the Temporal deployment."
display_name = "Temporal database configuration"

[[input]]
name         = "temporal_db_instance_type"
description  = "What RDS DB instance type would you like to deploy for temporal?"
default      = "db.t4g.medium"
display_name = "RDS Instance Type"
group        = "rds-temporal"


# 3-clickhouse.toml
#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "clickhouse"
description  = "Configuration for the clickhouse cluster Nuon will create for itself. The default password is autogenerated."
display_name = "ClickHouse cluster configuration."

[[input]]
name         = "ch_instance_type_cluster"
description  = "What EC2 instance type should each clickhouse cluster node deploy on?"
default      = "t3a.large"
display_name = "Cluster Instance Type"
group        = "clickhouse"

[[input]]
name         = "ch_instance_type_keeper"
description  = "What EC2 instance type should each clickhouse cluster node deploy on?"
default      = "t3a.medium"
display_name = "Keeper Instance Type"
group        = "clickhouse"


# 4-auth.toml
#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "auth"
description  = "Configure authentication for your Nuon install."
display_name = "Nuon Authentication configuration."

[[input]]
name         = "auth_issuer_url"
description  = "Auth0 Issuer URL - include trailing slash."
default      = "https://your-tenant-name.us.auth0.com/"
display_name = "Auth0 Issuer URL"
group        = "auth"

[[input]]
name         = "auth_audience"
description  = "Auth0 Audience"
default      = "api.{{.nuon.install.id}}.nuon.run"
display_name = "Auth0 Audience"
group        = "auth"

[[input]]
name         = "auth_client_id_ctl_api"
description  = "Auth0 Client ID for the CTL API"
default      = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
display_name = "Auth0 Client ID - CTL API"
group        = "auth"

[[input]]
name         = "auth_client_id_dashboard_ui"
description  = "Auth0 Client ID for the Dashboard UI"
default      = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
display_name = "Auth0 Client ID - Dashboard UI"
group        = "auth"


# 5-nuon.toml
#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "nuon"
description  = "Configure your Nuon install."
display_name = "Nuon configuration"

[[input]]
name         = "env"
description  = "The nuon env. One of: dev, prod. If unsure, it's prod."
default      = "prod"
display_name = "Environement"
group        = "nuon"


# 6-github.toml
#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "github"
description  = "Configure the GitHub Application for this BYOC Nuon install."
display_name = "Github | Nuon configuration"

[[input]]
name         = "github_app_name"
description  = "The name of the GitHub app to use for VCS connections."
default      = "byocnuon/my-org-connect"
display_name = "GitHub App Name"
group        = "github"

[[input]]
name         = "github_app_id"
description  = "The github app id."
default      = "0000000"
display_name = "GitHub App ID"
group        = "github"

[[input]]
name         = "github_app_client_id"
description  = "The github app client id."
default      = "xxxxxxxxxxxxxxxxxxxx"
display_name = "GitHub App Client ID"
group        = "github"


# 7-dns.toml
#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "dns"
description  = "DNS Configrations"
display_name = "Configurations for the root domain for Route53"

[[input]]
name         = "root_domain"
description  = "The root domain. Services will be made available at subdomains of this root domain."
default      = "byoc.for.everyone.example.com"
display_name = "Root Domain"
group        = "dns"
