# sandbox
terraform_version = "1.11.3"

[public_repo]
directory = "."
repo      = "nuonco/aws-eks-karpenter-sandbox"
branch    = "v1.7.0"

[vars]
cluster_version = "1.34"
cluster_name    = "n-{{.nuon.install.id}}"

enable_nuon_dns      = "true"
public_root_domain   = "{{ .nuon.inputs.inputs.root_domain }}"
internal_root_domain = "internal.{{ .nuon.inputs.inputs.root_domain }}"

karpenter_version = "1.7.4"

default_instance_type = "m6a.large"
min_size              = "2"
max_size              = "4"

[[var_file]]
#:schema https://api.nuon.co/v1/general/config-schema?type=sandbox
contents = "./sandbox.tfvars"
