[[secret]]
name                        = "github_app_key_{{.nuon.id}}"
display_name                = "GitHub App Key"
description                 = "Github App Key for BYOC Nuon Install {{.nuon.id}}"
required                    = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "github_app_key"


[[secret]]
name                        = "tfe_orgs_workspace_id_{{.nuon.id}}"
display_name                = "TFE Orgs Workspace ID"
description                 = "TFE Work Workspace ID for BYOC Nuon Install {{.nuon.id}}"
required                    = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "tfe-orgs-workspace-id"


[[secret]]
name                        = "tfe_token_{{.nuon.id}}"
display_name                = "TFE Token"
description                 = "TFE Token for BYOC Nuon Install {{.nuon.id}}"
required                    = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "tfe-orgs-workspace-id"

# Auth0 Secrets

[[secret]]
name                        = "auth0_client_secret_{{.nuon.id}}"
display_name                = "Auth0 Client Secret"
description                 = "Auth0 Client Secret for BYOC Nuon Install {{.nuon.id}}"
required                    = true
kubernetes_secret_namespace = "dashboard-ui"
kubernetes_secret_name      = "dashboard-ui-auth0-secret"

[[secret]]
name                        = "auth0_client_secret_{{.nuon.id}}"
display_name                = "Auth0 Secret"
description                 = "Auth0 Secret for BYOC Nuon Install {{.nuon.id}}"
required                    = true
kubernetes_secret_namespace = "dashboard-ui"
kubernetes_secret_name      = "dashboard-ui-auth0-client-secret"
