[[secret]]
name                        = "github_app_key_{{.nuon.id}}"
display_name                = "GitHub App Key for {{.nuon.id}}"
description                 = "Github App Key"
required                    = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "github_app_key"
