[[secret]]
name         = "github_app_key"
display_name = "GitHub App Key"
description  = "Github App Key for BYOC Nuon Install {{.nuon.id}}"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "github-app-key"


[[secret]]
name         = "tfe_orgs_workspace_id"
display_name = "TFE Orgs Workspace ID"
description  = "TFE Work Workspace ID for BYOC Nuon Install {{.nuon.id}}"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "tfe-orgs-workspace-id"


[[secret]]
name         = "tfe_token"
display_name = "TFE Token"
description  = "TFE Token for BYOC Nuon Install {{.nuon.id}}"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "tfe-orgs-token"

# Auth0 Secrets

[[secret]]
name          = "auth0_secret"
display_name  = "Auth0 Secret"
description   = "Auth0 Client Secret for BYOC Nuon App - app.{{.nuon.id}}.nuon.run"

kubernetes_sync             = true
kubernetes_secret_namespace = "dashboard-ui"
kubernetes_secret_name      = "dashboard-ui-auth0-secret"

[[secret]]
name          = "auth0_client_secret"
display_name  = "Auth0 Client Secret"
description   = "A long secret value used to encrypt the session cookie. e.g. openssl rand -hex 32"
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "dashboard-ui"
kubernetes_secret_name      = "dashboard-ui-auth0-client-secret"

# ClickHouse Secrets

[[secret]]
name          = "clickhouse_operator_pw"
display_name  = "Clickhouse Operator Password"
description   = "Password for the Clickhouse Operator Deployment"
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "clickhouse"
kubernetes_secret_name      = "clickhouse-operator-pw"

[[secret]]
name          = "clickhouse_cluster_pw"
display_name  = "Clickhouse Cluster Password"
description   = "Password for the Clickhouse Cluster for the Nuon CTL API User."
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "clickhouse"
kubernetes_secret_name      = "clickhouse-cluster-pw"

[[secret]]
name          = "clickhouse_cluster_ro_pw"
display_name  = "Clickhouse Cluster Read-only Password"
description   = "Password for the Clickhouse Cluster for the Nuon CTL API Read only User."
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "clickhouse"
kubernetes_secret_name      = "clickhouse-cluster-ro-pw"
