[[secret]]
name         = "github_app_key_{{.nuon.id}}"
display_name = "GitHub App Key"
description  = "Github App Key for BYOC Nuon Install {{.nuon.id}}"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "github-app-key"


[[secret]]
name         = "tfe_orgs_workspace_id_{{.nuon.id}}"
display_name = "TFE Orgs Workspace ID"
description  = "TFE Work Workspace ID for BYOC Nuon Install {{.nuon.id}}"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "tfe-orgs-workspace-id"


[[secret]]
name         = "tfe_token_{{.nuon.id}}"
display_name = "TFE Token"
description  = "TFE Token for BYOC Nuon Install {{.nuon.id}}"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "tfe-orgs-token"

# Auth0 Secrets

[[secret]]
name         = "auth0_client_secret_{{.nuon.id}}"
display_name = "Auth0 Client Secret"
description  = "Auth0 Client Secret for BYOC Nuon Install {{.nuon.id}}"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "dashboard-ui"
kubernetes_secret_name      = "dashboard-ui-auth0-secret"

[[secret]]
name         = "auth0_client_secret_{{.nuon.id}}"
display_name = "Auth0 Secret"
description  = "Auth0 Secret for BYOC Nuon Install {{.nuon.id}}"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "dashboard-ui"
kubernetes_secret_name      = "dashboard-ui-auth0-client-secret"

# ClickHouse Secrets

[[secret]]
name          = "clickhouse_operator_pw_{{.nuon.id}}"
display_name  = "Clickhouse Operator Password"
description   = "Password for the Clickhouse Operator Deployment"
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "clickhouse"
kubernetes-secret-name      = "clickhouse-operator-pw"

[[secret]]
name          = "clickhouse_cluster_pw_{{.nuon.id}}"
display_name  = "Clickhouse Cluster Password"
description   = "Password for the Clickhouse Cluster for the Nuon CTL API User."
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "clickhouse"
kubernetes-secret-name      = "clickhouse-cluster-pw"

[[secret]]
name          = "clickhouse_cluster_ro_pw_{{.nuon.id}}"
display_name  = "Clickhouse Cluster Read-only Password"
description   = "Password for the Clickhouse Cluster for the Nuon CTL API Read only User."
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "clickhouse"
kubernetes-secret-name      = "clickhouse-cluster-ro-pw"
