name         = "install_stack_template_bucket_region"
description  = "The region of the bucket for the install templates used in cloudformation for AWS installs."
default      = ""
display_name = "Install Stack Template Bucket Region"
required     = false
group        = "nuon"
type         = "string"

user_configurable = false
