name         = "nuon_access_secret_arn"
description  = "ARN of the AWS Secrets Manager secret in the central account that holds an identity provider configuration for Nuon Access."
default      = ""
display_name = "Nuon Access Secrets ARN"
required     = false
group        = "nuon"

user_configurable = false
