# action
# description: temporal hard-reset step 4 — recreates the required Temporal namespaces.
name    = "temporal_hard_reset_ensure_namespaces"
labels  = { service = "temporal", type = "step" }
timeout = "1m30s"

[[triggers]]
type = "manual"

[[steps]]
name    = "Ensuring Namespaces"
command = "./temporal/ensure_namespaces.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "shared/src/actions"
branch    = "am/gcp-scoped-roles"
