#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "uninstall_helm_chart"
labels  = { service = "kubernetes", type = "sop" }
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "uninstall-helm-chart"
inline_contents = "./kubectl/uninstall_helm_chart/uninstall-helm-chart.sh"

[steps.env_vars]
NAMESPACE = ""
CHART_NAME = ""
