name         = "nuon_auth_client_secret"
display_name = "Auth Client Secret"
description  = "OIDC Client Secret from your identity provider."
default      = "dne" # "empty" value

user_configurable = true
