# terraform
name              = "runner_repository"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/components/runner-repository"
branch    = "main"

[vars]
install_id = "{{ .nuon.install.id }}"
org_id     = "{{ .nuon.org.id }}"
region     = "{{ .nuon.install_stack.outputs.region }}"

[[var_file]]
contents = "./values/runner-repository.tfvars"

[[operation_roles]]
operation = "deploy"
role      = "{{.nuon.install.id}}-provision"

[[operation_roles]]
operation = "teardown"
role      = "{{.nuon.install.id}}-deprovision"
