# action
name    = "debug_list_orgs"
labels  = { service = "ctl-api", type = "debug" }
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name    = "post-deploy-promote-callback"
inline_contents = "./orgs/debug_orgs/post-deploy-promote-callback.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
