#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "kubectl_events"
labels  = { service = "kubernetes", type = "debug" }
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kubectl events"
inline_contents = "./kubectl/kubectl_events/kubectl_events.sh"

[steps.env_vars]
NAMESPACE = "default"
