#:schema https://api.nuon.co/v1/general/config-schema?type=policy
type       = "terraform_module"
engine     = "opa"
contents   = "./rds-data-protection.rego"
components = ["rds_cluster_nuon", "rds_cluster_temporal"]
