type           = "provision"
name           = "{{.nuon.install.id}}-provision"
description    = "Provision role for BYOC Nuon"
display_name   = "Provision"
cloud_platform = "gcp"

[[policies]]
name                = "owner"
gcp_predefined_role = "roles/owner"
