# action
name    = "kubectl_list_nodepools"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kubectl list nodepools"
inline_contents = "./kubectl/kubectl_list_nodepools/kubectl_list_nodepools.sh"

[steps.env_vars]
NAMESPACE = "default"
