name         = "auth0_client_secret"
display_name = "Auth0 Client Secret"
description  = "Auth0 Single-Page App Client Secret"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "datadog"
kubernetes_secret_name      = "datadog-app-key"
