name         = "datadog_api_key"
display_name = "Datadog API Key"
description  = "Datadog API Key"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "datadog"
kubernetes_secret_name      = "datadog-api-key"
