# action
name    = "ch_restart_keeper"
labels  = { layer = "infra", purpose = "sop" }
timeout = "3m"

[[triggers]]
type = "manual"

[[steps]]
name            = "restart"
inline_contents = "./clickhouse/ch_restart_keeper/restart.sh"
