#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "azure_rbac_access"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon-azure/src/components/azure_rbac_access"
branch    = "ht/azure"

[vars]
subscription_id = "{{ .nuon.cloud_account.azure.subscription_id }}"
resource_group_name = "{{ .nuon.install_stack.outputs.resource_group_name }}"
aks_cluster_id = "{{ .nuon.sandbox.outputs.cluster.id }}"
maintenance_principal_object_id = "{{ .nuon.install.inputs.maintenance_principal_object_id }}"
break_glass_principal_object_id = "{{ .nuon.install.inputs.break_glass_principal_object_id }}"
