#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name           = "rds_subnet"
type           = "helm_chart"
chart_name     = "empty"
namespace      = "default"
storage_driver = "configmap"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon-azure/src/components/empty-chart"
branch    = "ht/azure"
