#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "ctl_api_query_phone_home"
labels  = { service = "ctl-api", type = "tool" }
timeout = "120s"

[[triggers]]
type = "manual"

[[steps]]
name            = "Query phone home requests"
inline_contents = "./ctl_api/ctl_api_query_phone_home/query-phone-home.sh"

[steps.env_vars]
DB_USER          = "{{ .nuon.components.ctl_api_wi.outputs.db_user }}"
CTL_API_SA_EMAIL = "{{ .nuon.components.ctl_api_wi.outputs.service_account_email }}"
DB_NAME    = "ctl_api"
DB_ADDR    = "{{ .nuon.components.cloudsql_nuon.outputs.address }}"
DB_PORT    = "5432"
INSTALL_ID = ""
