#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "auth0_module"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/auth0_provider"
branch    = "tw/auth0-module"

[vars]
# Required Auth0 Configuration
auth0_domain = "your-tenant.auth0.com"  # Replace with your Auth0 domain
auth0_client_id = ""  # Replace with your Auth0 Management API Client ID
auth0_client_secret = ""  # Replace with your Auth0 Management API Client Secret
tenant_name = "{{ .nuon.install.name }}"  # Will use Nuon install name as tenant name

# Optional Configuration (with defaults)
session_lifetime = 72  # Session lifetime in hours
allow_signup = false  # Whether to allow user signup

