#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "auth0_module"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/auth0_provider"
branch    = "tw/auth0-module"

[vars]
# Required Auth0 Configuration
auth0_domain = "{{ .nuon.inputs.inputs.auth_issuer_url }}"  
auth0_mgmt_client_id = "{{ .nuon.inputs.inputs.auth0_mgmt_client_id }}"  
auth0_mgmt_client_secret = "{{ .nuon.inputs.inputs.auth0_mgmt_client_secret }}"
auth0_audience = "https://api.{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"  
public_domain = "{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"
internal_domain = "{{ .nuon.install.sandbox.outputs.nuon_dns.internal_domain.name }}"
install_name="{{ .nuon.install.name }}"
callback_url = "https://app.{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}/api/auth/callback"
logout_url = "https://app.{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"
web_origin = "https://app.{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"
