#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "auth0_module"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/auth0_provider"
branch    = "tw/auth0-module"

[vars]
# Required Auth0 Configuration
auth0_domain = "{{ .nuon.inputs.inputs.auth_issuer_url }}"  # Replace with your Auth0 domain
auth0_mgmt_client_id = "{{ .nuon.inputs.inputs.auth0_mgmt_client_id }}"  # Replace with your Auth0 Management API Client ID
auth0_mgmt_client_secret = "{{ .nuon.inputs.inputs.auth0_mgmt_client_secret }}"  # Replace with your Auth0 Management API Client Secret
