#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "management"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/management"
branch    = "a370eebe672e20e712181bfc06ab1edf3793eb9a"

[vars]
foo = "bar"

[[var_file]]
contents = "./values/management.tfvars"
