#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "rds_cluster_nuon"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
directory = "aws/rds-cluster"
repo      = "nuonco/components"
branch    = "69eb6535a5db0b1cfe74fabe204b15ace622fe66"

[vars]
identifier      = "nuon-{{ .nuon.install.id }}"
port            = "5432"
db_name         = "ctl_api"
db_user         = "ctl_api"
instance_class  = "{{ .nuon.install.inputs.nuon_db_instance_type }}"
subnet_group_id = "{{ .nuon.components.components.rds_subnet.outputs.id }}"

region     = "{{ .nuon.install_stack.outputs.region }}"
vpc_id     = "{{ .nuon.install_stack.outputs.vpc_id }}"
subnet_ids = "{{ index .nuon.sandbox.outputs.vpc.private_subnet_ids 0}},{{ index .nuon.sandbox.outputs.vpc.private_subnet_ids 1 }},{{ index .nuon.sandbox.outputs.vpc.private_subnet_ids 2 }}"

nuon_id = "{{ .nuon.install.id }}"
