#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "rds_cluster_temporal"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
directory = "aws/rds-cluster"
repo      = "nuonco/components"
branch    = "e6ba0eb18ee2a4e7b9f3970fefeae336829d4e1a"

[vars]
identifier      = "temporal-{{ .nuon.install.id }}"
port            = "5432"
db_name         = "temporal"
db_user         = "temporal"
instance_class  = "{{ .nuon.install.inputs.temporal_db_instance_type }}"
subnet_group_id = "{{ .nuon.components.components.rds_subnet.outputs.id }}"

region     = "{{ .nuon.install_stack.outputs.region }}"
vpc_id     = "{{ .nuon.install_stack.outputs.vpc_id }}"
subnet_ids = "{{ index .nuon.sandbox.outputs.vpc.private_subnet_ids 0}},{{ index .nuon.sandbox.outputs.vpc.private_subnet_ids 1 }},{{ index .nuon.sandbox.outputs.vpc.private_subnet_ids 2 }}"

nuon_id = "{{ .nuon.install.id }}"
