#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "rds_secrets"
type              = "terraform_module"
terraform_version = "1.11.3"

dependencies = ["rds_cluster_nuon", "rds_cluster_temporal"]

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/rds_secrets"
branch    = "main"

[vars]
region                             = "{{ .nuon.install_stack.outputs.region }}"
cluster_name                       = "{{.nuon.install.sandbox.outputs.cluster.name}}"
cluster_endpoint                   = "{{.nuon.install.sandbox.outputs.cluster.endpoint}}"
cluster_certificate_authority_data = "{{.nuon.install.sandbox.outputs.cluster.certificate_authority_data}}"

[[var_file]]
contents = "./values/rds-secrets.tfvars"
