name           = "ctl_api_init_db"
type           = "helm_chart"
chart_name     = "clt-api-init"
storage_driver = "configmap"
namespace      = "ctl-api"

dependencies   = ["rds_cluster_nuon"]

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/ctl_api_init_db"
branch    = "main"

[[values_file]]
contents = "./values/ctl-api-init.yaml"
