name           = "temporal_init_db"
type           = "helm_chart"
chart_name     = "temporal-init-db"
storage_driver = "configmap"
namespace      = "temporal"

dependencies   = ["karpenter_nodepools", "rds_cluster_temporal"]

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/temporal_init_db"
branch    = "fd/temporal/db-refinements"

[[values_file]]
contents = "./values/temporal-init.yaml"
