#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name           = "storage_classes"
type           = "helm_chart"
chart_name     = "storage-classes"
storage_driver = "configmap"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/storage_classes"
branch    = "main"

[[values_file]]
contents = """
region: "{{ .nuon.install_stack.outputs.region }}"
"""
