name = "img_nuon_ctl_api"
type = "container_image"

[aws_ecr]
image_url = "431927561584.dkr.ecr.us-west-2.amazonaws.com/mono/ctl-api"
tag          = "0.19.668"
region = "us-west-2"
iam_role_arn = "arn:aws:iam::431927561584:role/nuon-ecr-access"
