#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "crd_external_secrets"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/external_secrets_operator"
branch    = "main"

[vars]
crd_version = "v0.16.1"

nuon_install_id = "{{ .nuon.install.id }}"
region          = "{{ .nuon.install_stack.outputs.region }}"

cluster_name                       = "{{.nuon.install.sandbox.outputs.cluster.name}}"
cluster_endpoint                   = "{{.nuon.install.sandbox.outputs.cluster.endpoint}}"
cluster_certificate_authority_data = "{{.nuon.install.sandbox.outputs.cluster.certificate_authority_data}}"
