name              = "temporal"
type              = "terraform_module"
terraform_version = "1.11.3"
dependencies      = ["karpenter_nodepools", "temporal_init_db"]

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/temporal"
branch    = "fd/temporal/simplify-helm-provider"

[vars]
env    = "prod"
region = "{{ .nuon.install_stack.outputs.region }}"
zone   = "{{ .nuon.install.sandbox.outputs.nuon_dns.internal_domain.name }}"

codec_endpoint = "https://app.{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}/admin/temporal-codec"
ctl_api_host   = "api.{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"

temporal_pw_secret_arn            = '{{ .nuon.install_stack.outputs.temporal_temporal_pw_arn }}'
temporal_visibility_pw_secret_arn = '{{ .nuon.install_stack.outputs.temporal_visibility_pw_arn }}'
db_instance_address               = "{{ .nuon.components.rds_cluster_temporal.outputs.address }}"
db_instance_port                  = "{{ .nuon.components.rds_cluster_temporal.outputs.db_instance_port }}"

temporal_web_image_repository = '{{ .nuon.components.img_temporal_ui.outputs.image.repository }}'
temporal_web_image_tag        = '{{ .nuon.components.img_temporal_ui.outputs.image.tag }}'

temporal_server_image_repository = '{{ .nuon.components.img_temporal_server.outputs.image.repository }}'
temporal_server_image_tag        = '{{ .nuon.components.img_temporal_server.outputs.image.tag }}'

temporal_admin_tools_image_repository ='{{ .nuon.components.img_temporal_admin_tools.outputs.image.repository }}'
temporal_admin_tools_image_tag        ='{{ .nuon.components.img_temporal_admin_tools.outputs.image.tag }}'
