#:schema https://api.nuon.co/v1/general/config-schema?source=helm
name           = "external_secrets_operator"
type           = "helm_chart"
chart_name     = "external-secrets-operator"
storage_driver = "configmap"
namespace      = "external-secrets"

[public_repo]
repo      = "external-secrets/external-secrets"
directory = "deploy/charts/external-secrets"
branch    = "v0.16.1"

[[values_file]]
contents = "./values/external-secrets.yaml"
