#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "clickhouse_cluster"
type              = "terraform_module"
terraform_version = "1.11.3"

dependencies = ["crd_clickhouse_operator", "karpenter_nodpools"]

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/clickhouse_cluster"
branch    = "main"

[vars]
env                                = "prod"
install_id                         = "{{ .nuon.install.id }}"
region                             = "{{ .nuon.install_stack.outputs.region }}"
zone                               = "{{ .nuon.install.sandbox.outputs.nuon_dns.internal_domain.name }}"
cluster_name                       = "{{ .nuon.install.sandbox.outputs.cluster.name }}"
cluster_endpoint                   = "{{ .nuon.install.sandbox.outputs.cluster.endpoint }}"
cluster_certificate_authority_data = "{{ .nuon.install.sandbox.outputs.cluster.certificate_authority_data }}"
cluster_oidc_provider              = "{{ .nuon.install.sandbox.outputs.cluster.oidc_provider }}"

clickhouse_role_arn          = "{{ .nuon.components.s3_buckets.outputs.clickhouse_bucket_role.arn }}"
clickhouse_s3_bucket_id      = "{{ .nuon.components.s3_buckets.outputs.clickhouse_bucket.id }}"
cluster_image_repository     = "{{ .nuon.components.img_clickhouse_server.outputs.image.repository }}"
cluster_image_tag            = "{{ .nuon.components.img_clickhouse_server.outputs.image.tag }}"
keeper_image_repository      = "{{ .nuon.components.img_clickhouse_keeper.outputs.image.repository }}"
keeper_image_tag             = "{{ .nuon.components.img_clickhouse_keeper.outputs.image.tag }}"
