#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "ctl_api_role"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/ctl_api_role"
branch    = "main"

[vars]
install_id              = "{{ .nuon.install.id }}"
region                  = "{{ .nuon.install_stack.outputs.region }}"
cluster_name            = "{{ .nuon.install.sandbox.outputs.cluster.name }}"
db_instance_resource_id = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_resource_id }}"
