#:schema https://api.nuon.co/v1/general/config-schema?source=helm
name           = "ctl_api"
type           = "helm_chart"
chart_name     = "ctl-api"
namespace      = "ctl-api"
storage_driver = "configmap"
dependencies   = ["rds_cluster_nuon", "karpenter_nodepools", "clickhouse_cluster", "temporal", "management", "ctl_api_init_db"]

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/ctl_api"
branch    = "tw/runner-tag-input"

[[values_file]]
contents = "./values/ctl-api.yaml"
