name           = "empty_chart"
type           = "helm_chart"
chart_name     = "ctl-api"
namespace      = "ctl-api"
storage_driver = "configmap"
dependencies   = ["rds_cluster_nuon"]

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/components/ctl_api"
branch    = "jm/empty"

[[values_file]]
inline_contents = """
env:
   FOO: bar
"""
