# helm
name           = "storage_classes"
type           = "helm_chart"
chart_name     = "storage-classes"
storage_driver = "configmap"

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/components/storage_classes"
# TEMP: carries the kafka-gp3 storage class. Revert to main once it merges.
branch    = "ey/kafka-strimzi"

[[values_file]]
contents = """
region: "{{ .nuon.install_stack.outputs.region }}"
"""
