#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "auth"
description  = "Auth0 Configuration"
display_name = "Nuon: Auth0"

[[input]]
name         = "auth_issuer_url"
description  = "Auth0 Issuer URL - include trailing slash."
default      = "https://your-tenant-name.us.auth0.com/"
display_name = "Auth0 Issuer URL"
group        = "auth"

[[input]]
name         = "auth_audience"
description  = "Auth0 Audience"
default      = "api.{{.nuon.install.id}}.nuon.run"
display_name = "Auth0 Audience"
group        = "auth"

[[input]]
name         = "auth_client_id_ctl_api"
description  = "Auth0 Client ID for the CTL API"
default      = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
display_name = "Auth0 Client ID - CTL API"
group        = "auth"

[[input]]
name         = "auth_client_id_dashboard_ui"
description  = "Auth0 Client ID for the Dashboard UI"
default      = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
display_name = "Auth0 Client ID - Dashboard UI"
group        = "auth"
