#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "github"
description  = "Configure the GitHub Application for this BYOC Nuon install."
display_name = "Nuon: Github App"

[[input]]
name         = "github_app_name"
description  = "The name of the GitHub app to use for VCS connections."
default      = ""
display_name = "GitHub App Name"
group        = "github"
required     = true

[[input]]
name         = "github_app_id"
description  = "The github app id."
default      = ""
display_name = "GitHub App ID"
group        = "github"
required     = true

[[input]]
name         = "github_app_client_id"
description  = "The github app client id."
default      = ""
display_name = "GitHub App Client ID"
group        = "github"
required     = true
