name         = "github_app_key"
display_name = "GitHub App Key"
description  = "Base64 encoded Github App Key"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "github-app-key"
format = "base64"

