# action
name    = "temporal_hard_reset_scale_down_ctl_api_workers"
labels  = { service = "temporal", type = "step" }
timeout = "1m30s"

[[triggers]]
type = "manual"

[[steps]]
name            = "Scale Down ctl-api workers"
inline_contents = "./temporal/temporal_hard_reset_scale/scale_down_ctl_api_workers.sh"
