#:schema https://api.nuon.co/v1/general/config-schema?type=policy
type       = "terraform_module"
engine     = "opa"
contents   = "./clickhouse-backups-present.rego"
components = ["clickhouse_cluster"]
