#:schema https://api.nuon.co/v1/general/config-schema?type=policy
# `sandbox` policies evaluate the sandbox run; the `components` field is ignored.
type     = "sandbox"
engine   = "opa"
contents = "./gke-endpoint-access.rego"
