#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "kubectl"
labels  = { service = "kubernetes", type = "tool" }
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kubectl"
inline_contents = "./kubectl/kubectl/kubectl.sh"

[steps.env_vars]
CMD = "get ns"
