# action
name    = "kubectl"
labels  = { service = "kubernetes", purpose = "tool" }
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kubectl"
inline_contents = "./kubectl/kubectl/kubectl.sh"

[steps.env_vars]
CMD = "get ns"
