#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "ctl_api_query_workflow_steps"
labels  = { service = "ctl-api", type = "tool" }
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name            = "Query workflow steps"
inline_contents = "./ctl_api/ctl_api_query_workflow_steps/query-workflow-steps.sh"

[steps.env_vars]
DB_USER    = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_username }}"
DB_NAME    = "ctl_api"
SECRET_ARN = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_master_user_secret_arn }}"
DB_ADDR    = "{{ .nuon.components.rds_cluster_nuon.outputs.address }}"
DB_PORT    = "5432"
REGION     = "{{ .nuon.install_stack.outputs.region }}"
LIMIT      = "1"

[[steps]]
name            = "timestamp"
inline_contents = "./ctl_api/ctl_api_query_workflow_steps/timestamp.sh"
