region       = "{{ .nuon.install_stack.outputs.region }}"
install_id   = "{{ .nuon.install.id }}"
org_id       = "{{ .nuon.org.id }}"
zone_id      = "{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.zone_id }}"
zone_name    = "{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"
alb_dns_name = "{{ .nuon.components.public_ingress.outputs.alb_dns_name }}"
alb_zone_id  = "{{ .nuon.components.public_ingress.outputs.alb_zone_id }}"
