#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "helm_list"
labels  = { service = "kubernetes", type = "debug" }
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "helm"
inline_contents = "./kubectl/helm_history/helm.sh"

[steps.env_vars]
NAMESPACE = ""
CHART_NAME = ""
