#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
# description: takes a deliberate manual snapshot of the Temporal RDS instance
# and waits for it to complete. First step of the Temporal RDS teardown.
name    = "rds_backup_temporal"
labels  = { service = "rds", type = "sop" }
label   = "aws"
timeout = "60m"
role    = "{{.nuon.install.id}}-rds-operations"

[[triggers]]
type = "manual"

[[steps]]
name            = "Backup Temporal RDS"
inline_contents = "./rds/rds_backup/rds_backup.sh"

[steps.env_vars]
DB_RESOURCE_ID = "{{ .nuon.components.rds_cluster_temporal.outputs.db_instance_resource_id }}"
DB_LABEL       = "temporal"
