# action
# description: terminates a list of Temporal workflows (workflow ids as csv) in a namespace.
name    = "temporal_terminate_workflows_by_id"
label   = "temporal"
timeout = "10m"

[[triggers]]
type = "manual"

[[steps]]
name = "terminate workflows"
inline_contents = "./temporal/temporal_terminate_workflows_by_id/terminate_workflows.sh"

[steps.env_vars]
NAMESPACE = "general"
# comma-separated list of workflow ids to terminate
WORKFLOW_IDS = ""
REASON = "terminated via temporal_terminate_workflows_by_id action"
