#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "task_iam"
type              = "terraform_module"
terraform_version = "1.11.3"
dependencies      = ["ctl_api_db", "object_storage"]

[public_repo]
repo      = "nuonco/byoc"
directory = "nuon-lite/components/task-iam"
branch    = "ja/aws-ecs"

[[var_file]]
contents = "./task-iam/task-iam.tfvars"
