region                         = "{{ .nuon.install_stack.outputs.region }}"
install_id                     = "{{ .nuon.install.id }}"
org_id                         = "{{ .nuon.org.id }}"
aurora_credentials_secret_arn  = "{{ .nuon.components.ctl_api_db.outputs.credentials_secret_arn }}"
clickhouse_password_secret_arn = "{{ .nuon.install_stack.outputs.clickhouse_cloud_password_arn }}"
blob_bucket_arn                = "{{ .nuon.components.object_storage.outputs.blob_bucket_arn }}"
install_templates_bucket_arn   = "{{ .nuon.components.object_storage.outputs.install_templates_bucket_arn }}"
clickhouse_backup_bucket_arn   = "{{ .nuon.components.object_storage.outputs.clickhouse_backup_bucket_arn }}"
