#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "billing_alarm"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "nuon-lite/components/billing-alarm"
branch    = "ja/aws-ecs"

[[var_file]]
contents = "./billing-alarm/billing-alarm.tfvars"
