#:schema http://localhost:8081/v1/general/config-schema?type=input-groups
name         = "clickhouse"
description  = "ClickHouse runs as a single-node Fargate task with managed EBS."
display_name = "ClickHouse"
