#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "ctl_api"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "nuon-lite/components/ctl-api"
branch    = "ja/aws-ecs"

[[var_file]]
contents = "./ctl-api/ctl-api.tfvars"
