#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "route53"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/byoc"
directory = "nuon-byoc-aws-ecs/src/components/route53"
branch    = "ja/aws-ecs"

[[var_file]]
contents = "./values/route53.tfvars"
