name          = "temporal_temporal_pw"
display_name  = "Temporal Password"
description   = "Password for the temporal user for access to temporal db."
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "temporal"
kubernetes_secret_name      = "temporal-temporal-db-pw"
