name          = "temporal_visibility_pw"
display_name  = "Visibility Password"
description   = "Password for the temporal user for access to the visibility db."
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "temporal"
kubernetes_secret_name      = "temporal-visibility-db-pw"
