#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
# description: fetches ctl-api version and runs route healthchecks for the
# public, admin (private), and runner HTTPRoutes.
name    = "api_status"
labels  = { service = "ctl-api", type = "debug" }
timeout = "2m"

[[triggers]]
type          = "cron"
cron_schedule = "10,40 * * * *"

[[triggers]]
type = "manual"

[[steps]]
name            = "fetch ctl-api version"
inline_contents = "./ctl_api/api_status/version.sh"

[steps.env_vars]
API_URL = "https://api.{{ .nuon.sandbox.outputs.nuon_dns.public_domain.name }}"

[[steps]]
name            = "route-healthcheck-ctl-api-public"
inline_contents = "./ctl_api/api_status/healthcheck.sh"

[steps.env_vars]
ROUTE_NAME      = "ctl-api-public"
ROUTE_NAMESPACE = "ctl-api"

[[steps]]
name            = "route-healthcheck-ctl-api-admin"
inline_contents = "./ctl_api/api_status/healthcheck.sh"

[steps.env_vars]
ROUTE_NAME      = "ctl-api-admin"
ROUTE_NAMESPACE = "ctl-api"

[[steps]]
name            = "route-healthcheck-ctl-api-runner"
inline_contents = "./ctl_api/api_status/healthcheck.sh"

[steps.env_vars]
ROUTE_NAME      = "ctl-api-runner"
ROUTE_NAMESPACE = "ctl-api"

[[steps]]
name            = "timestamp"
inline_contents = "./ctl_api/api_status/timestamp.sh"
