# action
# description: ensures all required Temporal namespaces exist after Temporal deploys.
name    = "temporal_drop_namespaces"
labels  = { service = "temporal", type = "sop", temporal = "true" }
timeout = "10m"

[[triggers]]
type = "manual"

[[steps]]
name    = "dropping namespaces"
command = "./temporal/drop_namespaces.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "shared/src/actions"
branch    = "lovable-runtime-sa"
