name         = "datadog_network_monitoring_enabled"
description  = "Enable Datadog DNS and network metrics collection (system-probe DNS stats and AWS ENA metrics)."
default      = "false"
display_name = "Datadog Network Monitoring Enabled"
required     = false
group        = "datadog"
type         = "bool"

user_configurable = true
