name         = "github_app_name"
description  = "The name of the GitHub app to use for VCS connections."
default      = "please-provide-a-value"
display_name = "GitHub app name"
group        = "github"
required     = true

user_configurable = true
