#:schema https://api.nuon.co/v1/general/config-schema?type=input
name         = "github_app_id"
description  = "The github app id."
default      = "please-provide-a-value"
display_name = "GitHub app ID"
group        = "github"
required     = true

user_configurable = true
