# action
name    = "kubectl_logs"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kubectl logs"
inline_contents = "./kubectl/kubectl_logs/kubectl_logs.sh"

[steps.env_vars]
NAMESPACE = "default"
