# action
name    = "delete_rds_snapshots"
labels  = { service = "rds", purpose = "sop" }
timeout = "10m"

[[triggers]]
type = "manual"

[[steps]]
name    = "delete_snapshots"
command = "./delete-snapshots.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions/rds"
branch    = "main"

[steps.env_vars]
SNAPSHOT_IDS = ""
