#:schema https://api.nuon.co/v1/general/config-schema?type=input
name         = "datadog_network_monitoring_enabled"
description  = "Enable Datadog DNS and network metrics collection (system-probe DNS stats)."
default      = "false"
display_name = "Datadog Network Monitoring Enabled"
required     = false
group        = "datadog"
type         = "bool"
