name         = "auth0_mgmt_client_secret"
description  = "Auth0 Management API Client Secret"
default      = "xxxxxxxxxx"
display_name = "Auth0 Management API Client Secret"
group        = "auth"
required     = true
sensitive    = true