# action
# description: execs into the temporal-init pod and runs the sql tools to
# create/migrate the temporal and temporal_visibility schemas, then creates
# dedicated db users for each database.
name    = "temporal_init_db"
timeout = "5m"

[[triggers]]
type           = "post-deploy-component"
component_name = "temporal_init_db"

[[triggers]]
type = "manual"

[[steps]]
name            = "Initialize the DB"
inline_contents = "./src/temporal/init-db.sh"

[[steps]]
name            = "Create DB Users"
inline_contents = "./src/temporal/create-db-users.sh"
