# action
name    = "runners_restart"
labels  = { service = "runners", type = "sop" }
timeout = "2m"

[[triggers]]
type = "manual"

[[steps]]
name = "orgs"
inline_contents = "./runners/runners_restart/orgs.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
