#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "kubectl_delete_nodepools"
labels  = { service = "kubernetes", type = "sop" }
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kubectl delete nodepools"
inline_contents = "./kubectl/kubectl_delete_nodepool/kubectl_delete_nodepools.sh"

[steps.env_vars]
NODEPOOL = "dne"
