name    = "run_clickhouse_init"
labels  = { service = "clickhouse", type = "ops" }
timeout = "10m"

[[triggers]]
type = "manual"

[[steps]]
name            = "run clickhouse init task"
inline_contents = "./ecs/run_aurora_init/run.sh"

[steps.env_vars]
CLUSTER  = "{{ .nuon.components.cluster.outputs.cluster_name }}"
TASK_DEF = "{{ .nuon.components.ecs_clickhouse_init.outputs.task_family }}"
SUBNETS  = "{{ .nuon.components.cluster.outputs.private_subnet_ids }}"
REGION   = "{{ .nuon.install_stack.outputs.region }}"
SG       = "{{ .nuon.components.ecs_ctl_api.outputs.security_group_id }}"
