# action
name    = "kubectl_events"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kubectl events"
inline_contents = "./kubectl/kubectl_events/kubectl_events.sh"

[steps.env_vars]
NAMESPACE = "default"
