#:schema https://api.nuon.co/v1/general/config-schema?type=input
name         = "slack_client_id"
description  = "The Slack app's OAuth Client ID. Found on the Slack app's Basic Information page."
default      = ""
display_name = "Slack client ID"
required     = false
group        = "slack"

user_configurable = false
