region            = "{{ .nuon.install_stack.outputs.region }}"
install_id        = "{{ .nuon.install.id }}"
org_id            = "{{ .nuon.org.id }}"
vpc_id            = "{{ .nuon.install_stack.outputs.vpc_id }}"
public_subnet_ids = "{{ .nuon.components.cluster.outputs.public_subnet_ids }}"
certificate_arn   = "{{ .nuon.components.certificate_wildcard_public.outputs.acm_certificate_arn }}"
