# action
name    = "db_access_disable"
labels  = { service = "db-access", type = "break-glass" }
timeout = "2m"
role    = "{{.nuon.install.id}}-provision"

[[triggers]]
type = "role-disabled"

[[triggers]]
type = "manual"

[[steps]]
name            = "Delete EKS access entry for db-access role"
inline_contents = "./db_access/db_access_disable/disable.sh"

[steps.env_vars]
CLUSTER_NAME = "n-{{ .nuon.install.id }}"
REGION       = "{{ .nuon.install_stack.outputs.region }}"
