name         = "secrets_role_arn"
description  = "ARN of the AWS IAM role this GCP install assumes to read vendor secrets from AWS Secrets Manager."
default      = ""
display_name = "Vendor secret store role ARN"
required     = false
group        = "secrets"

user_configurable = false
