#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "runners"
labels  = { service = "runners", type = "debug" }
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name            = "org"
inline_contents = "./runners/runner_details/admin-get.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
RUNNER_TYPE   = "org"

[[steps]]
name            = "install"
inline_contents = "./runners/runner_details/admin-get.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
RUNNER_TYPE   = "install"

[[steps]]
name = "settings"
inline_contents = "./runners/runner_details/settings.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
