# action
name    = "karpenter_rotate_nodepool"
labels  = { layer = "infra", purpose = "sop" }
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name = "karpenter_rotate_nodepool"
inline_contents = "./karpenter/karpenter_rotate_nodepool/rotate_nodepool.sh"

[steps.env_vars]
NODEPOOL_NAME = "dne"
