name          = "clickhouse_cluster_ro_pw"
display_name  = "Clickhouse Cluster Read-only Password"
description   = "Password for the Clickhouse Cluster for the Nuon CTL API Read only User."
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "clickhouse"
kubernetes_secret_name      = "clickhouse-cluster-ro-pw"

