name          = "clickhouse_operator_pw"
display_name  = "Clickhouse Operator Password"
description   = "Password for the Clickhouse Operator Deployment"
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "clickhouse"
kubernetes_secret_name      = "clickhouse-operator-pw"
