# action
name    = "karpenter_rotate_node"
labels  = { layer = "infra", purpose = "sop" }
timeout = "1m"

[[triggers]]
type = "manual"

[[steps]]
name = "karpenter_rotate_node"
inline_contents = "./karpenter/karpenter_rotate_node/rotate_node.sh"

[steps.env_vars]
NODE_NAME = "dne"
