# action
name    = "ch_restart_cluster"
labels  = { service = "clickhouse", type = "sop" }
timeout = "3m"

[[triggers]]
type = "manual"

[[steps]]
name            = "restart"
inline_contents = "./clickhouse/ch_restart_cluster/restart.sh"
