#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "ctl_api_post_deploy"
labels  = { service = "ctl-api", type = "step" }
timeout = "30m"

[[triggers]]
type           = "post-deploy-component"
component_name = "ctl_api"
index          = 5

[[triggers]]
type = "manual"

[[steps]]
name            = "restart-deployments"
inline_contents = "https://raw.githubusercontent.com/nuonco/actions/refs/heads/main/kube/deployments-restart"

[steps.env_vars]
NAMESPACE = "ctl-api"

[[steps]]
name            = "public-route-healthcheck"
inline_contents = "./ctl_api/ctl_api_post_deploy/healthcheck.sh"

[steps.env_vars]
ROUTE_NAME      = "ctl-api-public"
ROUTE_NAMESPACE = "ctl-api"

[[steps]]
name            = "runner-route-healthcheck"
inline_contents = "./ctl_api/ctl_api_post_deploy/healthcheck.sh"

[steps.env_vars]
ROUTE_NAME      = "ctl-api-runner"
ROUTE_NAMESPACE = "ctl-api"

[[steps]]
name            = "admin-route-healthcheck"
inline_contents = "./ctl_api/ctl_api_post_deploy/healthcheck.sh"

[steps.env_vars]
ROUTE_NAME      = "ctl-api-admin"
ROUTE_NAMESPACE = "ctl-api"

[[steps]]
name            = "runners-update-version"
inline_contents = "./ctl_api/ctl_api_post_deploy/update-version.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"

[[steps]]
name            = "promote-callback"
inline_contents = "./ctl_api/ctl_api_post_deploy/promote.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"

[[steps]]
name            = "get-migrations-callback"
inline_contents = "./ctl_api/ctl_api_post_deploy/get-migrations.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
