name              = "temporal"
type              = "terraform_module"
terraform_version = "1.11.3"
dependencies      = ["cloudsql_temporal", "temporal_init_db"]

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon-gcp/src/components/temporal"
branch    = "main"

[vars]
project_id = "{{ .nuon.install_stack.outputs.project_id }}"
region     = "{{ .nuon.install_stack.outputs.region }}"
zone       = "{{ .nuon.install.sandbox.outputs.nuon_dns.internal_domain.name }}"

cluster_endpoint                   = "{{ .nuon.install.sandbox.outputs.cluster.endpoint }}"
cluster_certificate_authority_data = "{{ .nuon.install.sandbox.outputs.cluster.certificate_authority_data }}"

codec_endpoint = "https://app.{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}/admin/temporal-codec"
ctl_api_host   = "api.{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"

db_instance_address    = "{{ .nuon.components.cloudsql_temporal.outputs.address }}"
db_instance_port       = "{{ .nuon.components.cloudsql_temporal.outputs.db_instance_port }}"
temporal_web_image_repository = "{{ .nuon.components.img_temporal_ui.outputs.image.repository }}"
temporal_web_image_tag        = "{{ .nuon.components.img_temporal_ui.outputs.image.tag }}"

temporal_server_image_repository = "{{ .nuon.components.img_temporal_server.outputs.image.repository }}"
temporal_server_image_tag        = "{{ .nuon.components.img_temporal_server.outputs.image.tag }}"

temporal_admin_tools_image_repository = "{{ .nuon.components.img_temporal_admin_tools.outputs.image.repository }}"
temporal_admin_tools_image_tag        = "{{ .nuon.components.img_temporal_admin_tools.outputs.image.tag }}"
