#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "ctl_api_wi"
type              = "terraform_module"
terraform_version = "1.11.3"
dependencies      = ["cloudsql_nuon"]

[public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon-gcp/src/components/ctl_api_wi"
branch    = "main"

[vars]
install_id             = "{{ .nuon.install.id }}"
project_id             = "{{ .nuon.install_stack.outputs.project_id }}"
cloudsql_instance_name = "{{ .nuon.components.cloudsql_nuon.outputs.db_instance_name }}"
