#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name           = "ctl_api"
type           = "helm_chart"
chart_name     = "ctl-api"
namespace      = "ctl-api"
storage_driver = "configmap"
dependencies   = ["cloudsql_nuon", "clickhouse_cluster", "temporal", "management", "ctl_api_init_db", "ctl_api_wi", "certificate_wildcard_public", "external_dns"]

[public_repo]
repo      = "nuonco/byoc"
directory = "shared/src/components/ctl_api"
branch    = "main"

[[values_file]]
contents = "./values/ctl-api.yaml"
