name        = "delete_event_loops"
description = "Check for stale EventLoop workflows in Temporal and delete them if found."
readme      = "./runbooks/delete_event_loops.md"
labels      = { service = "temporal", type = "tool" }

[[steps]]
name        = "Delete EventLoop workflows"
type        = "action"
action_name = "temporal_delete_event_loops"
