name        = "deploy_control_plane" # NOTE: "deploy_nuon", maybe?
description = "Deploys Nuon's ctl-api and dashboard-ui: syncs and rolls the CTL API, then the dashboard UI."
readme      = "./runbooks/deploy_control_plane.md"

[[steps]]
name           = "Sync dashboard image"
type           = "deploy"
component_name = "img_nuon_dashboard_ui"

[[steps]]
name           = "Sync image"
type           = "deploy"
component_name = "img_nuon_ctl_api"

[[steps]]
name        = "Initialize the ctl-api DB"
type        = "action"
action_name = "ctl_api_init_db"

[[steps]]
name        = "Initialize ClickHouse"
type        = "action"
action_name = "ch_init"

[[steps]]
name            = "Deploy helm chart"
type            = "deploy"
component_name  = "ctl_api"

[[steps]]
name        = "ctl-api post-deploy startup"
type        = "action"
action_name = "ctl_api_post_deploy_startup"

[[steps]]
name        = "ctl-api post-deploy"
type        = "action"
action_name = "ctl_api_post_deploy"

[[steps]]
name            = "Deploy dashboard helm chart"
type            = "deploy"
component_name  = "dashboard_ui"
