name        = "inspect_orgs"
description = "Inspect orgs — list all orgs, and inspect a single org's details."
readme      = "./runbooks/inspect_orgs.md"
labels      = { service = "ctl-api", type = "debug" }

[[steps]]
name        = "Inspect: orgs"
type        = "action"
action_name = "inspect_orgs"

[[steps]]
name        = "Inspect: org"
type        = "action"
action_name = "inspect_org"
