#:schema http://localhost:8081/v1/general/config-schema?type=inputs
name         = "ch_user"
description  = "ClickHouse user name used by ctl-api."
default      = "ctl_api"
display_name = "ClickHouse User"
group        = "clickhouse"

user_configurable = false
