#:schema https://api.nuon.co/v1/general/config-schema?type=inputs
name         = "cloudsql"
description  = "Configuration for the postgres database Nuon will create for itself."
display_name = "Nuon database configuration"
