name          = "aurora_master_username"
display_name  = "Aurora Master Username"
description   = "Master username for the Aurora Serverless v2 cluster."
auto_generate = false
default       = "nuon_admin"
