# action
name    = "ctl_api_startup"
labels  = { service = "ctl-api", type = "step" }
timeout = "1m30s"

[[triggers]]
type = "manual"

[[steps]]
name            = "Startup"
inline_contents = "./ctl_api/ctl_api_startup/startup.sh"

[steps.env_vars]
DB_ADDR = "{{ .nuon.components.cloudsql_nuon.outputs.address }}"
DB_PORT = "5432"

LOG_LEVEL      = "INFO"
DB_LOG_QUERIES = "false"
