#:schema https://api.nuon.co/v1/general/config-schema?type=action
# action
name    = "rds_monitor"
labels  = { service = "rds", type = "debug" }
timeout = "30s"
role = "{{.nuon.install.id}}-provision"

[[triggers]]
type = "manual"

[[steps]]
name            = "disk"
inline_contents = "./rds/rds_monitor/disk_metrics.sh"

[steps.env_vars]
DB_IDENTIFIER = "{{.nuon.components.rds_cluster_temporal.outputs.db_instance_name}}"

[[steps]]
name            = "status"
inline_contents = "./rds/rds_monitor/instance_status.sh"

[steps.env_vars]
DB_IDENTIFIER = "temporal-{{.nuon.install.id}}" # <- TODO(fd): modify the clusters so they emit this
