# action
name    = "ctl_api_post_deploy"
timeout = "5m"

[[triggers]]
type           = "post-deploy-component"
component_name = "ctl_api"
index          = 5

[[triggers]]
type = "manual"

[[steps]]
name            = "import-runner-image"
inline_contents = "./ctl_api/ctl_api_post_deploy/import.sh"

[steps.env_vars]
RUNNER_REPOSITORY_URI = "{{ .nuon.components.runner_repository.outputs.runner_repository.repository_uri }}"
OVERRIDE              = "false"

[[steps]]
name            = "restart-deployments"
inline_contents = "https://raw.githubusercontent.com/nuonco/actions/refs/heads/main/kube/deployments-restart"

[steps.env_vars]
NAMESPACE = "ctl-api"

[[steps]]
name            = "runners-update-version"
inline_contents = "./ctl_api/ctl_api_post_deploy/update-version.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"

[[steps]]
name            = "promote-callback"
inline_contents = "./ctl_api/ctl_api_post_deploy/promote.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"

[[steps]]
name            = "get-migrations-callback"
inline_contents = "./ctl_api/ctl_api_post_deploy/get-migrations.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"

[[steps]]
name            = "public-alb-healthcheck"
inline_contents = "./ctl_api/ctl_api_post_deploy/healthcheck.sh"

[steps.env_vars]
INGRESS_NAME      = "ctl-api-public"
INGRESS_NAMESPACE = "ctl-api"

[[steps]]
name            = "runner-alb-healthcheck"
inline_contents = "./ctl_api/ctl_api_post_deploy/healthcheck.sh"

[steps.env_vars]
INGRESS_NAME      = "ctl-api-runner"
INGRESS_NAMESPACE = "ctl-api"

[[steps]]
name            = "admin-alb-healthcheck"
inline_contents = "./ctl_api/ctl_api_post_deploy/healthcheck.sh"

[steps.env_vars]
INGRESS_NAME      = "ctl-api-admin"
INGRESS_NAMESPACE = "ctl-api"
