#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "alb_healthcheck_public"
timeout = "30s"

# [[triggers]]
# type          = "cron"
# cron_schedule = "0 */1 * * *"

[[triggers]]
type = "manual"

[[steps]]
name    = "alb-healthcheck-ctl-api-public"
inline_contents = """
#!/usr/bin/env sh

set +e
set -o pipefail
set -u

echo >&2 "fetching ingress data..."
ingress_json=`kubectl get --namespace $INGRESS_NAMESPACE ingress $INGRESS_NAME -o json | jq -c`
status=`echo $ingress_json |jq -c '.status'`
echo >&2 $status

echo >&2 "parsing status from ingress data..."
lb_ingress_count=`echo $status | jq '.loadBalancer.ingress | length'`
echo >&2 $lb_ingress_count
if [ "$lb_ingress_count" != "1" ];
  then
    indicator="🔴"
  else
    indicator="🟢"
fi
echo >&2 $indicator

echo >&2 "saving status to outputs..."
outputs=`jq --null-input --arg indicatorVar "$indicator" --argjson statusVar "$status" '{"status": $statusVar, "indicator": $indicatorVar}'`
echo $outputs >> $NUON_ACTIONS_OUTPUT_FILEPATH

echo >&2 "status is $indicator"
if [ "$indicator" = '"🔴"' ]; then
    echo >&2 "healthcheck failed, sending notification"
    TEXT=$(cat $outputs | jq -c . | jq -R .)
    PAYLOAD='{
        "channel": "'$CHANNEL'",
        "username": "BYOBot",
        "icon_emoji": ":'$EMOJI':",
        "text": '$TEXT'
    }'
    
    echo >&2 "sending message to Slack"
    curl -X POST -H 'Content-type: application/json' -d "$PAYLOAD" "$WEBHOOK_URL"

    # force this step to fail, so the correct status is displayed in the README
    exit 1
fi

echo >&2 "healthcheck succeeded, sending notification"
TEXT=$(cat $outputs | jq -c . | jq -R .)
PAYLOAD='{
    "channel": "'$CHANNEL'",
    "username": "BYOBot",
    "icon_emoji": ":'$EMOJI':",
    "text": '$TEXT'
}'

echo >&2 "sending message to Slack"
curl -X POST -H 'Content-type: application/json' -d "$PAYLOAD" "$WEBHOOK_URL"
"""
[steps.env_vars]
INGRESS_NAME      = "ctl-api-public"
INGRESS_NAMESPACE = "ctl-api"
WEBHOOK_URL = "https://hooks.slack.com/services/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"
CHANNEL = "jordan-test"
EMOJI = "nuon"
