#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "alb_healthcheck_public"
timeout = "30s"

# [[triggers]]
# type          = "cron"
# cron_schedule = "0 */1 * * *"

[[triggers]]
type = "manual"

[[steps]]
name    = "alb-healthcheck-ctl-api-public"
command = "./healthcheck.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
branch    = "fd/actions/split-up-alb-actions"
directory = "byoc-nuon/src/actions/alb"

[steps.env_vars]
INGRESS_NAME      = "ctl-api-public"
INGRESS_NAMESPACE = "ctl-api"
