#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "aws_subnet_ips"
timeout = "15s"

# [[triggers]]
# type          = "cron"
# cron_schedule = "0 */1 * * *"

[[triggers]]
type = "manual"

[[steps]]
name    = "check_subnet_ips"
command = "./subnet_ips.sh"

[steps.public_repo]
repo      = "nuonco/actions"
directory = "aws"
branch    = "main"
