#:schema https://api.nuon.co/v1/general/config-schema?type=action
name    = "ch_exec"
timeout = "60s"

[[triggers]]
type = "manual"

[[steps]]
name = "ch exec"
inline_contents = """
#!/usr/bin/env sh

pod=`kubectl -n clickhouse get pods | grep installation | cut -d ' ' -f 1 | tail -n 1`
set +x
kubectl --namespace=clickhouse exec -i $pod -- clickhouse client -d ctl_api -q "SYSTEM RESTORE REPLICA ON CLUSTER simple ctl_api.otel_log_records"
kubectl --namespace=clickhouse exec -i $pod -- clickhouse client -d ctl_api -q "SYSTEM RESTORE REPLICA ON CLUSTER simple ctl_api.otel_metrics_exponential_histogram"
kubectl --namespace=clickhouse exec -i $pod -- clickhouse client -d ctl_api -q "SYSTEM RESTORE REPLICA ON CLUSTER simple ctl_api.otel_metrics_gauge"
kubectl --namespace=clickhouse exec -i $pod -- clickhouse client -d ctl_api -q "SYSTEM RESTORE REPLICA ON CLUSTER simple ctl_api.otel_metrics_histogram"
kubectl --namespace=clickhouse exec -i $pod -- clickhouse client -d ctl_api -q "SYSTEM RESTORE REPLICA ON CLUSTER simple ctl_api.otel_metrics_sum"
kubectl --namespace=clickhouse exec -i $pod -- clickhouse client -d ctl_api -q "SYSTEM RESTORE REPLICA ON CLUSTER simple ctl_api.otel_traces"
kubectl --namespace=clickhouse exec -i $pod -- clickhouse client -d ctl_api -q "SYSTEM RESTORE REPLICA ON CLUSTER simple ctl_api.latest_runner_heart_beats"
"""

[steps.env_vars]
CLICKHOUSE_URL = "clickhouse.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
QUERY          = "SYSTEM RESTORE REPLICA ON CLUSTER simple ctl_api.otel_"
