#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "ctl_api_promote"
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name    = "post-deploy-promote-callback"
command = "./ctl_api/promote.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}:8082"


[[steps]]
name    = "post-deploy-get-migrations-callback"
command = "./ctl_api/migrations.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}:8082"
