#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "ctl_api_alb_healthcheck"
timeout = "30s"

# [[triggers]]
# type          = "cron"
# cron_schedule = "0 */1 * * *"

[[triggers]]
type = "manual"

[[steps]]
name    = "alb-healthcheck-ctl-api-public"
command = "./alb-healthcheck"

[steps.public_repo]
repo      = "nuonco/actions"
branch    = "main"
directory = "aws"

[steps.env_vars]
INGRESS_NAME      = "ctl-api-public"
INGRESS_NAMESPACE = "ctl-api"

[[steps]]
name    = "alb-healthcheck-ctl-api-runner"
command = "./alb-healthcheck"

[steps.public_repo]
repo      = "nuonco/actions"
branch    = "main"
directory = "aws"

[steps.env_vars]
INGRESS_NAME      = "ctl-api-runner"
INGRESS_NAMESPACE = "ctl-api"

[[steps]]
name    = "alb-healthcheck-dashboard-ui"
command = "./alb-healthcheck"

[steps.public_repo]
repo      = "nuonco/actions"
branch    = "main"
directory = "aws"

[steps.env_vars]
INGRESS_NAME      = "dashboard-ui"
INGRESS_NAMESPACE = "dashboard-ui"
