#:schema https://api.nuon.co/v1/general/config-schema?type=action
name    = "ctl_api_drop_table_temporal_payloads"
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name    = "Drop Table: temporal_payloads"
command = "./ctl_api/drop-table-temporal-payloads.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "fd/chore/db-tidbits"

[steps.env_vars]
DB_USER    = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_username }}"
DB_NAME    = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_name }}"
SECRET_ARN = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_master_user_secret_arn }}"
DB_ADDR    = "{{ .nuon.components.rds_cluster_nuon.outputs.address }}"
DB_PORT    = "5432"
REGION     = "{{ .nuon.install_stack.outputs.region }}"
