#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "ctl_api_delete_token"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name    = "Query the DB"
command = "./ctl_api/query-db.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "fd/action/query-db"

[steps.env_vars]
DB_USER    = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_username }}"
DB_NAME    = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_name }}"
SECRET_ARN = "{{ .nuon.components.rds_cluster_nuon.outputs.db_instance_master_user_secret_arn }}"
DB_ADDR    = "{{ .nuon.components.rds_cluster_nuon.outputs.address }}"
DB_PORT    = "5432"
REGION     = "{{ .nuon.install_stack.outputs.region }}"
QUERY      = "delete from tokens;"
