#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "ctl_api_init"
timeout = "1m30s"

[[triggers]]
type           = "pre-component-deploy"
component_name = "ctl_api"

[[triggers]]
type = "manual"

[[steps]]
name    = "Initialize the DB"
command = "./ctl_api/init.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
SECRET_ARN = "{{ .nuon.components.components.rds_cluster_nuon.outputs.db_instance_master_user_secret_arn }}"
DB_ADDR    = "{{ .nuon.components.components.rds_cluster_nuon.outputs.address }}"
DB_PORT    = "5432"
REGION     = "{{ .nuon.install_stack.outputs.region }}"
