#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "ctl_api_create_or_refresh_sa_token"
timeout = "10s"

[[triggers]]
type = "manual"

[[steps]]
name    = "create_or_refresh_sa_token"
command = "./ctl_api/create_or_refresh_sa_token.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}:8082"
ORG_ID        = ""
REFRESH       = "false"
