#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "ctl_api_add_support_users"
timeout = "10s"

[[triggers]]
type = "manual"

[[steps]]
name    = "support_users"
command = "./ctl_api/support-users.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}:8082"
OPERATION     = "add"
ORG_ID        = ""
