# action
name    = "ctl_api_promote"
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name            = "post-deploy-promote-callback"
inline_contents = "./src/ctl-api/promote.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"


[[steps]]
name            = "post-deploy-get-migrations-callback"
inline_contents = "./src/ctl-api/get-migrations.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
