#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "deployments_restart"
timeout = "0m30s"

[[triggers]]
type = "manual"

[[triggers]]
type           = "post-deploy-component"
component_name = "ctl_api"

[[steps]]
name    = "deployments_restart"
command = "./deployments-restart"

[steps.public_repo]
repo      = "nuonco/actions"
branch    = "main"
directory = "kube"

[steps.env_vars]
NAMESPACE = "ctl-api"
