#:schema https://api.nuon.co/v1/general/config-schema?type=action
name    = "forget_org"
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name    = "forget-org"
inline_contents = """
#!/usr/bin/env sh

set -e
set -o pipefail
set -u

admin_api_addr="$ADMIN_API_URL"

curl --max-time 5 -q \
  "$admin_api_addr/v1/orgs/$org_id/forget" \
  | jq .
"""

[steps.env_vars]
ORG_ID = ""
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
