#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "generate_ch_cluster_reader_secret"
timeout = "1m30s"

[[triggers]]
type = "pre-sandbox-run"

[[triggers]]
type = "manual"

[[steps]]
name    = "Generate CH Cluster Reader Secrets"
command = "./gen_username_and_password_secret"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]

REGION          = "{{ .nuon.install_stack.outputs.region }}"
REGENERATE      = "false"
NUON_INSTALL_ID = "{{ .nuon.install.id }}"
SECRET_NAME     = "nuon-gen/clickhouse-cluster-ro-{{ .nuon.install.id }}"
USERNAME        = "clickhousero"

