# action
name    = "karpenter_nodepools"
timeout = "20s"


[[triggers]]
type          = "cron"
cron_schedule = "55 */1 * * *"

[[triggers]]
type = "manual"

[[steps]]
name            = "list"
inline_contents = "./src/karpenter/nodepools.sh"
