#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "kill_namespace_pods"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name    = "kill-namespace-pods"
inline_contents = """
#!/usr/bin/env sh
kubectl \
  --namespace $NAMESPACE \
  get pods \
  -o name | \
  \xargs -n 1 \
  kubectl \
  delete \
  -n $NAMESPACE \
  --grace-period=0 \
  --force
"""

[steps.env_vars]
NAMESPACE         = ""
