#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "kill_pods_in_namespace"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kill-pods-in-namespace"
inline_content = """
#!/usr/bin/env sh
kubectl \
  --namespace $NAMESPACE \
  get pods \
  -o name | \
  xargs -n 1 \
  kubectl \
  delete \
  -n $NAMESPACE \
  --grace-period=0 \
  --force
"""

[steps.env_vars]
NAMESPACE = ""
