#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "kubectl_get_pods"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kubectl get pods"
inline_contents = """
#!/usr/bin/env sh
kubectl get pods -A
"""

[steps.env_vars]
NAMESPACE = "default"
