#:schema https://api.nuon.co/v1/general/config-schema?type=action
name    = "kubectl_get_pods"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "kubectl get pods"
inline_contents = """
#!/usr/bin/env sh
kubectl --namespace $NAMESPACE get pods
kubectl --namespace $NAMESPACE get pods  -o json | jq -c >> $NUON_ACTIONS_OUTPUT_FILEPATH
"""

[steps.env_vars]
NAMESPACE = "ctl-api"
