#:schema https://api.nuon.co/v1/general/config-schema?type=action
name    = "preflight"
timeout = "1m"

# [[triggers]]
# type           = "post-sandbox-run"

[[triggers]]
type = "manual"

[[steps]]
name    = "Ensure Secrets Access is Denied: Auth0 Client Secret ARN"
command = "./preflight/ensure-secrets-access.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
SECRET_ARN = "{{.nuon.install_stack.outputs.auth0_client_secret_arn }}" # cannot read
REGION     = "{{ .nuon.install_stack.outputs.region }}"

[[steps]]
name    = "Ensure Secrets Access is Denied: Clickhouse Cluster r/w Secret"
command = "./preflight/ensure-secrets-access.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
SECRET_ARN = "{{.nuon.install_stack.outputs.clickhouse_cluster_pw_arn }}" # cannot read
REGION     = "{{ .nuon.install_stack.outputs.region }}"

[[steps]]
name    = "Ensure Secrets Access is Denied: Clickhouse Operator Secret"
command = "./preflight/ensure-secrets-access.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
SECRET_ARN = "{{.nuon.install_stack.outputs.clickhouse_operator_pw_arn }}" # cannot read
REGION     = "{{ .nuon.install_stack.outputs.region }}"
