#:schema https://api.nuon.co/v1/general/config-schema?source=action
# description: copies the secret from Secrets Manager into the k8s cluster.
# TODO: replace this with an external-secrets SecretStore
name    = "preflight"
timeout = "1m"

# [[triggers]]
# type           = "post-sandbox-run"

[[triggers]]
type = "manual"

[[steps]]
name    = "Ensure Secrets Access"
command = "./preflight/ensure-secrets-access.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
AUTH0_CLIENT_SECRET_ARN = "{{.nuon.install_stack.outputs.auth0_client_secret_arn }}" # cannot read
REGION                  = "{{ .nuon.install_stack.outputs.region }}"
