#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "runners_monitor"
timeout = "5m"

[[triggers]]
type = "manual"

# TODO(fd): add cron trigger

[[steps]]
name = "check_org_runner_deployments"
command = "./monitor.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions/runners"
branch    = "main"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
