# action
name    = "runner_extend_token"
timeout = "10s"

[[triggers]]
type = "manual"

[[steps]]
name            = "extend_token"
inline_contents = "./src/runners/extend_token.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
RUNNER_ID        = ""
