# action
name    = "runners_monitor"
timeout = "5m"

[[triggers]]
type = "manual"

# TODO(fd): add cron trigger

[[steps]]
name            = "org"
inline_contents = "./src/runners/check-org-runners-statuses.sh"

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
