# action
# description: temporal hard-reset step 6 — reprovisions every org via admin API.
name    = "temporal_hard_reset_reprovision_orgs"
timeout = "5m"

[[triggers]]
type = "manual"

[[steps]]
name = "reprovision_orgs"
inline_contents = """
#!/usr/bin/env bash

set -e
set -o pipefail
set -u

admin_api_url="$ADMIN_API_URL"

echo "[reprovision-orgs] fetching all orgs"
real_orgs=$(curl --max-time 5 -s "$admin_api_url/v1/orgs?type=real" | jq -c)
default_orgs=$(curl --max-time 5 -s "$admin_api_url/v1/orgs?type=default" | jq -c)
orgs=$(echo "$real_orgs $default_orgs" | jq -s 'add' -c)

for org_id in $(echo "$orgs" | jq -r '.[].id'); do
  echo " > reprovisioning org: $org_id"
  curl -X 'POST' -s -q \
    "$admin_api_url/v1/orgs/$org_id/admin-reprovision" \
    -H 'accept: application/json' \
    -H 'X-Nuon-Admin-Email: jon@nuon.co' \
    -H 'Content-Type: application/json' \
    -d '{}'
done

echo "[reprovision-orgs] done"
"""

[steps.env_vars]
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
