#:schema https://api.nuon.co/v1/general/config-schema?type=action
name    = "temporal_cli"
timeout = "10m"

[[triggers]]
type = "manual"

[[steps]]
name    = "temporal-cli"
inline_contents = """
#!/usr/bin/env sh

set -e
set -o pipefail
set -u
set -x

echo '{{ .nuon.components.img_temporal_server.outputs }}'

echo "Downloading Temporal CLI..."
curl "https://temporal.download/cli/archive/latest?platform=linux&arch=amd64" -o /tmp/temporal-cli.tar.gz
tar -xzf /tmp/temporal-cli.tar.gz -C /tmp


echo "Executing command..."

address="temporal-frontend-headless.temporal.svc.cluster.local:7233"
echo >&2 "using address $address"

echo >&2 "fetching the workflow $NAMESPACE.$WORKFLOW_ID"
kubectl -n temporal exec -i deployment/temporal-admintools -- \
    temporal workflow --address $address --namespace $NAMESPACE describe --workflow-id $WORKFLOW_ID
"""

[steps.env_vars]
NAMESPACE="installs"
WORKFLOW_ID="inllrk7qamfcwvrn7rb4ot7c75-execute-workflow-inwfq1pf93f0uo30p8c4k97g3m"
