# action
name    = "temporal_expose"
timeout = "20m" # TODO: determine how long this action should actually last
role    = "byoc-nuon-break-glass-{{ .nuon.install.id }}"

[[triggers]]
type = "manual"

[[steps]]
name            = "port-forward"
inline_contents = "./src/temporal/port-forward.sh"

[steps.env_vars]
NAMESPACE   ="temporal"
SERVICE     ="temporal-frontend-headless"
REMOTE_PORT ="7233"
LOCAL_PORT  = "7233"
