#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "temporal_init"
timeout = "1m30s"

[[triggers]]
type           = "pre-component-deploy"
component_name = "temporal"

[[triggers]]
type = "manual"

[[steps]]
name    = "Initialize the DB"
command = "./temporal/init.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
DB_HOST         = "{{ .nuon.components.components.rds_cluster_temporal.outputs.address }}"
DB_PORT         = "5432"
DB_SECRET_ARN   = "{{ .nuon.components.components.rds_cluster_temporal.outputs.db_instance_master_user_secret_arn }}"
NUON_INSTALL_ID = "{{ .nuon.install.id }}"
REGION          = "{{ .nuon.install_stack.outputs.region }}"
CLUSTER_NAME    = "{{ .nuon.sandbox.outputs.cluster.name }}"
ROLE            = "{{ .nuon.install_stack.outputs.maintenance_iam_role_arn }}"
