#:schema https://api.nuon.co/v1/general/config-schema?type=action
name    = "temporal_ensure_namespaces"
timeout = "1m30s"

[[triggers]]
type           = "post-deploy-component"
component_name = "temporal"

[[triggers]]
type = "manual"

[[steps]]
name    = "Ensuring Namespaces"
command = "./temporal/ensure_namespaces.sh"

[steps.public_repo]
repo      = "nuonco/byoc"
directory = "byoc-nuon/src/actions"
branch    = "main"

[steps.env_vars]
FOO = "BAR"
