name         = "nuon_access_secret_arn"
description  = "ARN of the AWS Secrets Manager secret in the central account describing this install's identity providers. Read by the sync_auth_providers action."
default      = ""
display_name = "Nuon Access Secrets ARN"
required     = false
group        = "nuon"
type         = "string"

user_configurable = false
